### ISSUE TITLE
Please specify a license

### ISSUE THREAD

**Issue by juan-garcia-m** [metaborg/coronium#2]
This repository does not contains a license.

Without a license cloning or using the software is not implicitly granted, which it is not an ideal situation on GitHub for a public repository.

A MIT style license would be greatly appreciated, but even if the software is proprietary a license or EULA will clarify what can be done with the software for those of us who are interested in using it.

**Comment by Gohla** [comment]
Good point, I forgot to add a license. It is now licensed under Apache 2.0, since that is what we use here at our group.
